# crypto-config.yaml

OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: AAUI
    Domain: aaui.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"

  - Name: AAJI
    Domain: aaji.org
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"

PeerOrgs:
  # ---------------------------------------------------------------------------
  # Prudential
  # ---------------------------------------------------------------------------
  - Name: prudential
    Domain: prudential.aaui.org
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Manulife
  # ---------------------------------------------------------------------------
  - Name: manulife
    Domain: manulife.aaui.org
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Allianz
  # ---------------------------------------------------------------------------
  - Name: allianz
    Domain: allianz.aaui.org
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
